#Use matrix to speed up the build process
strategy:
  matrix:
    TARGET_MDE:
      Build.Pkgs: 'MdePkg MdeModulePkg'
    TARGET_OTHER:
      Build.Pkgs: 'MsUnitTestPkg NetworkPkg PcAtChipsetPkg'
    TARGET_SECURITY_CPU:
      Build.Pkgs: 'SecurityPkg UefiCpuPkg'

workspace:
  clean: all

steps:
- checkout: self
  clean: true
  
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.7.x'
    architecture: 'x64'

- script: . gccinstall.sh
  displayName: 'Install GCC'

- script: pip3 install -r requirements.txt --upgrade
  displayName: 'Install/Upgrade mu_build'

#Build repo
- task: CmdLine@1
  displayName: Build and Test $(Build.Pkgs)
  inputs:
    filename: mu_build
    arguments: -c linux_ci.mu.yaml --force-git -p $(Build.Pkgs) TOOL_CHAIN_TAG=GCC5 CONF_TEMPLATE_DIR=BaseTools/LinuxConf/build_rule.template.ms # Optional

# Publish Test Results to Azure Pipelines/TFS
- task: PublishTestResults@2
  displayName: 'Publish junit test results'
  continueOnError: true
  condition: succeededOrFailed()
  inputs:
    testResultsFormat: 'JUnit' # Options: JUnit, NUnit, VSTest, xUnit
    testResultsFiles: 'Build/BuildLogs/TestSuites.xml' 
    #searchFolder: '$(System.DefaultWorkingDirectory)' # Optional
    mergeTestResults: true # Optional
    #testRunTitle: # Optional
    #buildPlatform: # Optional
    #buildConfiguration: # Optional
    publishRunAttachments: true # Optional
   

# Publish Build Artifacts
# Publish build artifacts to Azure Artifacts/TFS or a file share
- task: PublishBuildArtifacts@1
  displayName: 'Publish build logs'
  continueOnError: true
  condition: succeededOrFailed()
  inputs:
    pathtoPublish: 'Build/BuildLogs' 
    artifactName: 'Build Logs $(Build.Pkgs)' 
    #publishLocation: 'Container' # Options: container, filePath
    #targetPath: # Required when publishLocation == FilePath
    #parallel: false # Optional
    #parallelCount: # Optional